### ISSUE TITLE
Why include Sho?

### ISSUE THREAD

**Issue by booch** [zverok/sho#1]
Is there any reason you chose to `include Sho` and then do `sho.template`, instead of just doing `Sho.template`? Seems like the latter would be more idiomatic Ruby.

**Comment by zverok** [comment]
Any metaprogramming-generated methods need a reference to a host module newly generated methods would be added to, and on `include Sho` the reference is passed implicitly (into `Sho.included`). With `Sho.template` calling convention, you'll need to pass "current module" explicitly:
```ruby
class MyClass
  Sho.template(self, :method_name, ...
```
...which is not convenient and not looking idiomatic.
